FROM node:16.13.1-alpine
WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig.json ./
COPY postcss.config.js ./
COPY webpack.config.ts ./
COPY .* ./
RUN npm install
EXPOSE 5000
CMD ["npm", "run", "dev"]