export const UPDATE_USER = 'UPDATE_USER';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_USER_INFO = 'SET_USER_INFO';
export const LOGOUT = 'LOGOUT';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
